name: "Planetary Technology"
highlighter: "rouge"
future: true
tagline: "Documentations"
image: "img/front.jpg"
repo: "planetarytechnology"
collections:
  space:
    output: true
  water:
    output: true
  power:
    output: true
