name: "Planetary Technology"
highlighter: "rouge"
future: true
repo: "planetarytechnology"
background: "/img/background.jpg"
collections:
  space:
    output: true
  water:
    output: true
  power:
    output: true
